[tools]
python = "latest"        # aws-cliよりも上に置くことで優先する
"npm:aws-cdk" = "latest"
aws-cli = "latest"
aws-vault = "latest"
bat = "latest"
biome = "latest"
chezmoi = "latest"
deno = "latest"
eza = "latest"
fd = "latest"
ffmpeg = "latest"
firebase = "latest"
gauche = "latest"
gcloud = "latest"
gemini-cli = "latest"
go = "latest"
golangci-lint = "latest"
hadolint = "latest"
hyperfine = "latest"
jnv = "latest"
jq = "latest"
neovim = "latest"
node = "latest"
pnpm = "latest"
ripgrep = "latest"
shellcheck = "latest"
tokei = "latest"
uv = "latest"
wasmer = "latest"
wasmtime = "latest"
wrk = "latest"
xc = "latest"
